// Generated by CoffeeScript 1.3.3
(function() {
  var models;

  models = require("../models/cards");

  exports.index = function(req, res) {
    res.send('Hello, World. Express!');
  };

  exports.api = function(req, res) {
    this.players = req.params.players;
    this.model = new models.Cards.Game(this.players);
    this.hands = this.model.deal();
    console.log(this.hands);
    res.send(this.hands);
  };

}).call(this);
