// Generated by CoffeeScript 1.3.3
(function() {
  var Cards, i, root, _, _nextId;

  _ = require("underscore");

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Cards = Cards = {};

  Cards.Rank = (function() {

    function Rank(value) {
      this.value = value;
    }

    Rank.prototype.letter = 'A23456789TJQK'.charAt(Rank.value);

    return Rank;

  })();

  Cards.Suit = (function() {

    function Suit(value) {
      this.value = value;
    }

    Suit.prototype.letter = 'CDHS'.charAt(Suit.value);

    Suit.prototype.color = Suit.letter === 'C' || Suit.letter === 'S' ? 'black' : 'red';

    Suit.prototype.name = Suit.letter === 'C' ? 'clubs' : Suit.letter === 'D' ? 'diams' : Suit.letter === 'H' ? 'hearts' : 'spades';

    return Suit;

  })();

  Cards.ranks = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i < 13; i = ++_i) {
      _results.push(new Cards.Rank(i));
    }
    return _results;
  })();

  Cards.suits = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i < 4; i = ++_i) {
      _results.push(new Cards.Suit(i));
    }
    return _results;
  })();

  _nextId = 0;

  Cards.Card = (function() {

    function Card(rank, suit) {
      this.rank = rank;
      this.suit = suit;
      this.id = "id" + (_nextId++);
    }

    return Card;

  })();

  Cards.Game = (function() {

    function Game(numberOfPlayers) {
      this.numberOfPlayers = numberOfPlayers != null ? numberOfPlayers : 4;
      this.players = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.numberOfPlayers; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push([]);
        }
        return _results;
      }).call(this);
      this.deck = _.shuffle(this.createDeck());
    }

    Game.prototype.deal = function() {
      var deckCopy, spareCards, _i, _ref;
      deckCopy = this.deck.slice(0);
      spareCards = deckCopy.length % this.numberOfPlayers;
      while (deckCopy.length - spareCards) {
        for (i = _i = 0, _ref = this.players.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          this.players[i].push(deckCopy.pop());
        }
      }
      this.spareCards = deckCopy;
      return this.players;
    };

    Game.prototype.createDeck = function() {
      var rank, suit;
      return _.flatten((function() {
        var _i, _len, _ref, _results;
        _ref = Cards.suits;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          suit = _ref[_i];
          _results.push((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = Cards.ranks;
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              rank = _ref1[_j];
              _results1.push(new Cards.Card(rank, suit));
            }
            return _results1;
          })());
        }
        return _results;
      })());
    };

    return Game;

  })();

}).call(this);
